### ISSUE TITLE
Ubuntu 20.04.1 images

### ISSUE THREAD

**Issue by velll** [ruby/ruby-docker-images#16]
Hey everyone!

Would you consider publishing focal-based images alongside with existing bionic-based ones?

Since 20.04 is an LTS and the 20.04.1 had shipped recently we're considering upgrading our infrastructure to focal.
We've been happy using your images for a while and would love to continue doing so. After all, 100K+ downloads on dockerhub is usually safer than going with our own.

**Comment by mrkn** [comment]
@velll We will migrate Ruby 3.0 image onto 20.04. Stay tuned.

**Comment by yahonda** [comment]
I think this request has been satisifid since https://github.com/ruby/ruby-docker-images/pull/20

```
$ docker run rubylang/ruby:3.0.0-focal ruby -v
... snip ...
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
$
```
