### ISSUE TITLE
Merge Dockerfile-arm64 and Dockerfile

### ISSUE THREAD

**Issue by sandstrom** [ruby/ruby-docker-images#30]
Since Docker supports multi-arch images, maybe you don't need to keep two Dockerfiles around?

I checked the diff between the two, and there isn't a huge delta. One package `g++` is missing and there are a few more lines being different.

Basically, if you put in e.g. `ubuntu:xenial` as the source, that source file will work with both arm and x64 (or any other supported architecture).

**Comment by hsbt** [comment]
Fixed by https://github.com/ruby/ruby-docker-images/pull/39

**Comment by sandstrom** [comment]
Awesome @hsbt 🎉
