### ISSUE TITLE
Add patch version in tag to avoid bundle ruby version dismatch

### ISSUE THREAD

**Issue by chloerei** [ruby/ruby-docker-images#33]
My Dockerfile:

```
FROM rubylang/ruby:3.1
```

The previous build was version 3.1.1, and it save to Gemfile.lock.

When docker image update to 3.1.2, CI throw error:

```
Your Ruby version is 3.1.2, but your Gemfile specified 3.1.1
```

Although I can update the Gemfile.lock locally and run CI again, it's annoying.

Is it possible to provide a patch version tag, such as rubylang:ruby:3.1.2 ?

---

I noticed that there is a tag rubylang/ruby:3.1.2-focal, it would be better to provide an alias as 3.1.2.

**Comment by hsbt** [comment]
I think you specified `ruby '3.1.1'` into your Gemfile. This error message is not related to the docker image.

**Comment by hsbt** [comment]
And we already provide the patch version as https://github.com/ruby/ruby-docker-images/pkgs/container/ruby/18896023?tag=3.1.2-focal

**Comment by chloerei** [comment]
The problem is:

- Dcokerfile `rubylang/ruby:3.1`
- Gemfile `ruby '3.1.1'`

CI pull the latest ruby:3.1 become ruby:3.1.2.

Use `3.1.2-focal` in Dockerfile solve the problem.
