### ISSUE TITLE
No ARM64 images available from the Docker registry

### ISSUE THREAD

**Issue by zedtux** [ruby/ruby-docker-images#35]
This issue is about 2 related issues :
* There's no arm64 docker image available from https://hub.docker.com/r/rubylang/ruby/tags
* The ARM64 docker image generated from the `Dockerfile-arm64` file are `linux/amd64` images even if they've been built on a M1 processor since the `multiarch/ubuntu-core:arm64-bionic` is a `linux/amd64` one

Changing the `Dockerfile-arm64` file `FROM` to `arm64v8/ubuntu:focal` (we need Ubuntu Focal in our case, not Bionic) builds a real `linux/arm64/v8` Docker image.

I could miss something and being wrong, so if it's the case please explain me how should the existing file work on ARM processors please.

**Comment by hsbt** [comment]
Can you try https://hub.docker.com/layers/rubylang/ruby/master-dev-64b6a018a38f200c957fdbbe7d0cbe0e64781c9f-jammy/images/sha256-c3f93990d9e77ce57222ead6adfe06d4edc3795561995735b16883d1cad85671?context=explore ?

I fixed multi arch images recently.

**Comment by zedtux** [comment]
Thanks @hsbt, I will give it a try!

**Comment by zedtux** [comment]
Actually the https://hub.docker.com/_/ruby repository provides ARM images.

What's the difference between that repository and yours please? When would make sense to use yours instead of theirs?
