### ISSUE TITLE
Will there be a 3.2.3-focal?

### ISSUE THREAD

**Issue by veganstraightedge** [ruby/ruby-docker-images#59]
We currently use `3.2.2-focal`.
We'd like to upgrade our Ruby from `3.2.2` to `3.2.3` (then on to `3..3`), but we'd like to do that separate from upgrading our Ubuntu version.

Is it possible to release a `3.2.2-focal` image please?

**Comment by hsbt** [comment]
Done https://github.com/ruby/ruby-docker-images/pkgs/container/ruby/170896541?tag=3.2.3-focal
