### ISSUE TITLE
`master-nightly-jammy` and `master-debug-nightly-jammy` have not been updated for 6 days

### ISSUE THREAD

**Issue by yahonda** [ruby/ruby-docker-images#78]
Rails Nightly CI https://buildkite.com/rails/rails-nightly uses `rubylang/ruby:master-nightly-jammy` and `rubylang/ruby:master-debug-nightly-jammy` images https://github.com/rails/buildkite-config/blob/1965f6690e7d04332224c20961d008b65b53d2f5/lib/buildkite/config/ruby_config.rb#L5-L6 .

I've found these images have not been updated for 6 days as of Feb 22, 2024.

- rubylang/ruby:master-nightly-jammy

https://hub.docker.com/layers/rubylang/ruby/master-nightly-jammy/images/sha256-c62cd2e4dfc58c8f02cfe83a8ea3c427e4e915c94facf5ba15736d32d6ea19d7?context=explore

- rubylang/ruby:master-debug-nightly-jammy

https://hub.docker.com/layers/rubylang/ruby/master-debug-nightly-jammy/images/sha256-d08facefd3feff9f4f02c1f94190337ddaa243d42f9a51a627e86e9a82ad68b3?context=explore

I wanted these images updated daily.

**Comment by hsbt** [comment]
Oh, Thank you. 

We should notify build fail to me. I will work it at first.

**Comment by hsbt** [comment]
@yahonda I fixed this. But the current image still have the following gabage that is provided by BASERUBY.

```
root@d513048806a1:/# ls /usr/local/include/
ruby-3.2.0  ruby-3.4.0+0
```

I will cleanup it.

**Comment by yahonda** [comment]
Thank you for the quick action.
Confirmed both images have been updated.

```
$ docker run --rm -t rubylang/ruby:master-nightly-jammy ruby -v
ruby 3.4.0dev (2024-02-22T02:51:30Z master 7acc8bbea5) [x86_64-linux]
```

```
$ docker run --rm -t rubylang/ruby:master-debug-nightly-jammy ruby -v
ruby 3.4.0dev (2024-02-22T02:51:30Z master 7acc8bbea5) [x86_64-linux]
```

So far, having unnecessary BASERUBY should not be an issue for Rails CI usage.
