### ISSUE TITLE
Ruby 3.3 + focal doesn't seem to be on Docker Hub

### ISSUE THREAD

**Issue by veganstraightedge** [ruby/ruby-docker-images#85]
Ubuntu 20.04 (focal) is listed on this repo's README:

https://github.com/ruby/ruby-docker-images?tab=readme-ov-file#ubuntu-2004-focal

And on the Dockerhub page 

https://hub.docker.com/r/rubylang/ruby

But doesn't seem to be in the collection of tagged images:

https://hub.docker.com/r/rubylang/ruby/tags?page=1&name=3.3

I was trying to upgrade our Rails app from 3.2.3 to 3.3.0 and neither of these packages can be found upstream in Docker Hub:

`rubylang/ruby:3.3-focal`
`rubylang/ruby:3.3.0-focal`

Thank you!

**Comment by hsbt** [comment]
@veganstraightedge Hi, Thank you for your report. I fixed and revised our workflows now. 

A new workflow pushed all of stable versions each Ubuntu images like https://github.com/ruby/ruby-docker-images/actions/runs/8182505349 .

Can you try again?

**Comment by veganstraightedge** [comment]
Thank you @hsbt! It's working as expected for me now. ❤️
