### ISSUE TITLE
Add another tag without Ubuntu codename

### ISSUE THREAD

**Issue by yahonda** [ruby/ruby-docker-images#93]
### Request
Add another tag `master-nightly` for `master-nightly-noble` and the future latest Ubuntu LTS codename.

### Background
Rails CI is making use of the docker images "rubylang/ruby:master-nightly-jammy" and "rubylang/ruby:master-debug-nightly-jammy" to make Rails support the latest master version of Ruby. It is really appreciated.

https://github.com/rails/buildkite-config/blob/a7289e196180246c129b3d262f79b3622675690b/lib/buildkite/config/ruby_config.rb#L5-L6

I assume once Ubuntu 24.04 is released,  "rubylang/ruby:master-nightly-noble" will be released. As Rails CI did change the tag name when the "rubylang/ruby:master-nightly-jammy" was available https://github.com/rails/buildkite-config/pull/49 . However, Rails CI concern is mainly about Ruby version on the newer version of os.  So it would be appreciated when the "rubylang/ruby:master-nightly-noble" is released, it has another tag "rubylang/ruby:master-nightly" without Ubuntu codename like "noble".

**Comment by hsbt** [comment]
Thanks for requesting that. I just fixed and released Noble image for testing.

https://github.com/ruby/ruby-docker-images/pull/96

**Comment by hsbt** [comment]
#98 will build noble image. Let me know if image is not available tomorrow.
